//
// Created by palma on 4/27/2025.
//

#ifndef BINARYSEARCHTREE_CONSTANTS_H
#define BINARYSEARCHTREE_CONSTANTS_H

#define MEMORY_ALLOCATION_ERROR_MESSAGE "Allocation error"
#define MEMORY_ALLOCATION_ERROR_CODE (-1)

#endif //BINARYSEARCHTREE_CONSTANTS_H
